### ISSUE TITLE
Implement code formatting guidelines (prettier) and code actions

### ISSUE THREAD

**Issue by aishenreemo** [FWDP/rantboard#5]
As what the title says...

**Comment by directormac** [comment]
@aishenreemo  sveltekit meron na po

**Comment by directormac** [comment]
@DDuran19  please do so on vanilla project.

**Comment by aishenreemo** [comment]
ako nalang, pati sa react, vanilla and vue.. gagawa rin ako instructions para sa pag-setup.

**Comment by DDuran19** [comment]
Yon naman pala e
